FROM node:20

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install
RUN npm install -pm2 -g

COPY . .

EXPOSE 3000

RUN HOST=43.201.59.121 PORT=12002 pm2 start socketServerLoc.js

CMD ["node", "app.js"]