FROM node:20

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install
RUN npm install --global pm2

COPY . .

EXPOSE 3000

# CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "production"]

CMD ["node", "app.js"]