//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TargetGrid_.h
//  Source: ssafy_msgs\msg\TargetGrid_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _TARGETGRID__H_
#define _TARGETGRID__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct TargetGrid_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs TargetGrid_
         {
               DDS::Double product_x_;
               DDS::Double product_y_;
               DDS::Double moving_zone_x_;
               DDS::Double moving_zone_y_;
               DDS::Double charge_x_;
               DDS::Double charge_y_;
         };

         typedef DDS_DCPSStruct_var < TargetGrid_> TargetGrid__var;
         typedef TargetGrid_&TargetGrid__out;
      }
   }
}




#endif
