//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WorkStatus_Dcps.h
//  Source: ssafy_msgs\msg\WorkStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _WORKSTATUS_DCPS_H_
#define _WORKSTATUS_DCPS_H_

#include "sacpp_mapping.h"
#include "WorkStatus_.h"
#include "dds_dcps.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_TypeSupportInterface;

         typedef WorkStatus_TypeSupportInterface * WorkStatus_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < WorkStatus_TypeSupportInterface> WorkStatus_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < WorkStatus_TypeSupportInterface> WorkStatus_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataWriter;

         typedef WorkStatus_DataWriter * WorkStatus_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < WorkStatus_DataWriter> WorkStatus_DataWriter_var;
         typedef DDS_DCPSInterface_out < WorkStatus_DataWriter> WorkStatus_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataReader;

         typedef WorkStatus_DataReader * WorkStatus_DataReader_ptr;
         typedef DDS_DCPSInterface_var < WorkStatus_DataReader> WorkStatus_DataReader_var;
         typedef DDS_DCPSInterface_out < WorkStatus_DataReader> WorkStatus_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataReaderView;

         typedef WorkStatus_DataReaderView * WorkStatus_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < WorkStatus_DataReaderView> WorkStatus_DataReaderView_var;
         typedef DDS_DCPSInterface_out < WorkStatus_DataReaderView> WorkStatus_DataReaderView_out;

         struct WorkStatus_Seq_uniq_ {};
         typedef DDS_DCPSUFLSeq < WorkStatus_, struct WorkStatus_Seq_uniq_> WorkStatus_Seq;
         typedef DDS_DCPSSequence_var < WorkStatus_Seq> WorkStatus_Seq_var;
         typedef DDS_DCPSSequence_out < WorkStatus_Seq> WorkStatus_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef WorkStatus_TypeSupportInterface_ptr _ptr_type;
            typedef WorkStatus_TypeSupportInterface_var _var_type;

            static WorkStatus_TypeSupportInterface_ptr _duplicate (WorkStatus_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static WorkStatus_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static WorkStatus_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static WorkStatus_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            WorkStatus_TypeSupportInterface_ptr _this () { return this; }


         protected:
            WorkStatus_TypeSupportInterface () {};
            ~WorkStatus_TypeSupportInterface () {};
         private:
            WorkStatus_TypeSupportInterface (const WorkStatus_TypeSupportInterface &);
            WorkStatus_TypeSupportInterface & operator = (const WorkStatus_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef WorkStatus_DataWriter_ptr _ptr_type;
            typedef WorkStatus_DataWriter_var _var_type;

            static WorkStatus_DataWriter_ptr _duplicate (WorkStatus_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static WorkStatus_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static WorkStatus_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static WorkStatus_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            WorkStatus_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const WorkStatus_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const WorkStatus_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const WorkStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const WorkStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const WorkStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const WorkStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const WorkStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const WorkStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const WorkStatus_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const WorkStatus_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (WorkStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const WorkStatus_& instance_data) = 0;

         protected:
            WorkStatus_DataWriter () {};
            ~WorkStatus_DataWriter () {};
         private:
            WorkStatus_DataWriter (const WorkStatus_DataWriter &);
            WorkStatus_DataWriter & operator = (const WorkStatus_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef WorkStatus_DataReader_ptr _ptr_type;
            typedef WorkStatus_DataReader_var _var_type;

            static WorkStatus_DataReader_ptr _duplicate (WorkStatus_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static WorkStatus_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static WorkStatus_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static WorkStatus_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            WorkStatus_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (WorkStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (WorkStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (WorkStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const WorkStatus_& instance) = 0;

         protected:
            WorkStatus_DataReader () {};
            ~WorkStatus_DataReader () {};
         private:
            WorkStatus_DataReader (const WorkStatus_DataReader &);
            WorkStatus_DataReader & operator = (const WorkStatus_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef WorkStatus_DataReaderView_ptr _ptr_type;
            typedef WorkStatus_DataReaderView_var _var_type;

            static WorkStatus_DataReaderView_ptr _duplicate (WorkStatus_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static WorkStatus_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static WorkStatus_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static WorkStatus_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            WorkStatus_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (WorkStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (WorkStatus_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (WorkStatus_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (WorkStatus_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const WorkStatus_& instance) = 0;

         protected:
            WorkStatus_DataReaderView () {};
            ~WorkStatus_DataReaderView () {};
         private:
            WorkStatus_DataReaderView (const WorkStatus_DataReaderView &);
            WorkStatus_DataReaderView & operator = (const WorkStatus_DataReaderView &);
         };

      }
   }
}




#endif
