//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WorkStatus_.h
//  Source: ssafy_msgs\msg\WorkStatus_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.9.190403OSS
//  
//******************************************************************
#ifndef _WORKSTATUS__H_
#define _WORKSTATUS__H_

#include "sacpp_mapping.h"
#include "ssafy_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace ssafy_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct WorkStatus_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_ssafy_msgs WorkStatus_
         {
               DDS::Boolean is_done_;
               DDS::Boolean is_start_;
         };

         typedef DDS_DCPSStruct_var < WorkStatus_> WorkStatus__var;
         typedef WorkStatus_&WorkStatus__out;
      }
   }
}




#endif
